default_language_version:
  python: python3.12.3

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Use the latest version of isort
    hooks:
      - id: isort

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
